version = 5.4.0
archive_dir = /etc/letsencrypt/archive/aaryaclothing.in
cert = /etc/letsencrypt/live/aaryaclothing.in/cert.pem
privkey = /etc/letsencrypt/live/aaryaclothing.in/privkey.pem
chain = /etc/letsencrypt/live/aaryaclothing.in/chain.pem
fullchain = /etc/letsencrypt/live/aaryaclothing.in/fullchain.pem
[renewalparams]
account = 93de2b700c81a4f71417e7e4c9c89484
http01_port = 80
pref_challs = http-01,
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
